version: "3.8"

services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3006:3006"
    networks:
      - nodeapp-network

  server:
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    networks:
      - nodeapp-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "0.0.0.0:5432:5432"
    env_file:
      - ./server/.env
    networks:
      - nodeapp-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    stop_grace_period: 1s

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "0.0.0.0:6379:6379"
    networks:
      - nodeapp-network
    stop_grace_period: 1s

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    env_file:
      - ./server/.env
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:rw
    ports:
      - 0.0.0.0:1888:1888 # pprof extension
      - 0.0.0.0:13133:13133 # health_check extension
      - 0.0.0.0:4318:4318 # OTLP http receiver
      - 0.0.0.0:55679:55679 # zpages extension
    networks:
      - nodeapp-network

networks:
  nodeapp-network:


