version: "3.8"

services:
  mainapp:
    build: ./
    container_name: mainapp
    ports:
      - "3000:3000"
    environment:
      REDISURL: redis
      DATABASE_HOST: postgres
      DATABASE_SSL: false
    networks:
      - nodeapp-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - nodeapp-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "0.0.0.0:6379:6379"
    networks:
      - nodeapp-network

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:rw
    ports:
      - 0.0.0.0:1888:1888 # pprof extension
      - 0.0.0.0:13133:13133 # health_check extension
      - 0.0.0.0:4318:4318 # OTLP http receiver
      - 0.0.0.0:55679:55679 # zpages extension
    networks:
      - nodeapp-network
    depends_on:
      - redis
      - postgres

networks:
  nodeapp-network:


