receivers:
  otlp:
    protocols:
      http:
  redis:
    endpoint: "redis:6379"
    collection_interval: 30s
  postgresql:
    endpoint: "postgres:5432"
    collection_interval: 30s
    username: ${username}
    password: ${password}
    databases: ${databses}
    tls:
      insecure: true

exporters:
  otlphttp:
    endpoint: https://otel.kloudmate.com:4318
    headers:
      Authorization: sk_qTNwGwVF67KAq2ZDm0DblSIe

processors:
  batch:

# extensions:
#   health_check:
#   pprof:
#   zpages:

service:
  # extensions: [pprof, zpages, health_check]
  pipelines:
    # traces:
    #   receivers: [redis, postgresql]
    #   processors: [batch]
    #   exporters: [otlphttp, logging]
    metrics:
      receivers: [redis, postgresql]
      processors: [batch]
      exporters: [otlphttp]
    # logs:
    #   receivers: [redis]
    #   processors: [batch]
    #   exporters: [otlphttp, logging]
