receivers:
  otlp:
    protocols:
      http:
  redis:
    endpoint: "redis:6379"
    collection_interval: 30s
  postgresql:
    endpoint: "postgres:5432"
    collection_interval: 30s
    username: ${username}
    password: ${password}
    databases: ${databses}
    tls:
      insecure: true

exporters:
  otlphttp:
    endpoint: https://otel.kloudmate.com:4318
    headers:
      Authorization: ${YOUR_WORKSPACE_SECRET_KEY}

processors:
  batch:

# extensions:
#   health_check:
#   pprof:
#   zpages:

service:
  # extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp, redis, postgresql]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
